"""add execution fields

Revision ID: 87004cf3c2f2
Revises: 0002_extend_job_status_lifecycle
Create Date: 2026-06-05 16:10:25.245710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003_add_execution_fields'
down_revision: Union[str, None] = '0002_extend_job_status_lifecycle'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "jobs",
        sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "jobs",
        sa.Column("max_retries", sa.Integer(), nullable=False, server_default="2"),
    )
    op.add_column(
        "jobs",
        sa.Column("timeout_seconds", sa.Integer(), nullable=False, server_default="300"),
    )
    op.add_column(
        "jobs",
        sa.Column("last_error", sa.Text(), nullable=True),
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'last_error')
    op.drop_column('jobs', 'timeout_seconds')
    op.drop_column('jobs', 'max_retries')
    op.drop_column('jobs', 'retry_count')
    # ### end Alembic commands ###
