"""add execution_mode and new fields

Revision ID: 2fb2ed7418c2
Revises: 003_add_execution_fields
Create Date: 2026-06-15 18:28:46.381711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004_add_workflow_ready_fields'
down_revision: Union[str, None] = '003_add_execution_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('execution_mode', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('scheduled_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'scheduled_time')
    op.drop_column('jobs', 'execution_mode')
    # ### end Alembic commands ###
