"""audit foundation

Revision ID: 28c39c6ee0ba
Revises: 6e43e87f42c0
Create Date: 2026-08-27 19:21:07.856320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c39c6ee0ba'
down_revision: Union[str, None] = '6e43e87f42c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('request_source', sa.String(length=50), nullable=True),
    sa.Column('request_reference', sa.String(length=255), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('target_host', sa.String(length=255), nullable=True),
    sa.Column('connection_method', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_job_id'), 'audit_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_audit_events_request_reference'), 'audit_events', ['request_reference'], unique=False)
    op.create_index(op.f('ix_audit_events_request_source'), 'audit_events', ['request_source'], unique=False)
    op.alter_column('jobs', 'request_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'request_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_audit_events_request_source'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_reference'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_job_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
