"""create_software_catalogue

Revision ID: 9a91edbf6e39
Revises: a809fac38d62
Create Date: 2026-08-31 18:37:33.321326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a91edbf6e39'
down_revision: Union[str, None] = 'a809fac38d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software_catalogue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('os_type', sa.String(length=50), nullable=False),
    sa.Column('request_source', sa.String(length=50), nullable=False),
    sa.Column('execution_mode', sa.String(length=50), nullable=False),
    sa.Column('target_port', sa.String(length=20), nullable=True),
    sa.Column('connection_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_catalogue_name'), 'software_catalogue', ['name'], unique=False)
    op.create_index(op.f('ix_software_catalogue_os_type'), 'software_catalogue', ['os_type'], unique=False)
    op.create_index(op.f('ix_software_catalogue_request_source'), 'software_catalogue', ['request_source'], unique=False)
    op.create_index(op.f('ix_software_catalogue_status'), 'software_catalogue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_software_catalogue_status'), table_name='software_catalogue')
    op.drop_index(op.f('ix_software_catalogue_request_source'), table_name='software_catalogue')
    op.drop_index(op.f('ix_software_catalogue_os_type'), table_name='software_catalogue')
    op.drop_index(op.f('ix_software_catalogue_name'), table_name='software_catalogue')
    op.drop_table('software_catalogue')
    # ### end Alembic commands ###
