"""add_notes_to_jobs

Revision ID: 255cda0c3fd2
Revises: 9a91edbf6e39
Create Date: 2026-09-01 12:03:19.765261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255cda0c3fd2'
down_revision: Union[str, None] = '9a91edbf6e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'notes')
    # ### end Alembic commands ###
