"""minimum decision ledger

Revision ID: 861e52f4c182
Revises: 28c39c6ee0ba
Create Date: 2026-08-28 19:35:06.797452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861e52f4c182'
down_revision: Union[str, None] = '28c39c6ee0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_ledger',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('request_source', sa.String(length=50), nullable=False),
    sa.Column('request_reference', sa.String(length=255), nullable=True),
    sa.Column('requested_by', sa.String(length=100), nullable=True),
    sa.Column('software_name', sa.String(length=255), nullable=True),
    sa.Column('target_host', sa.String(length=255), nullable=True),
    sa.Column('connection_method', sa.String(length=50), nullable=True),
    sa.Column('authorization_result', sa.String(length=20), nullable=True),
    sa.Column('authorization_reason', sa.Text(), nullable=True),
    sa.Column('execution_path', sa.String(length=100), nullable=True),
    sa.Column('execution_result', sa.String(length=50), nullable=True),
    sa.Column('execution_details', sa.Text(), nullable=True),
    sa.Column('verification_result', sa.String(length=50), nullable=True),
    sa.Column('verification_details', sa.Text(), nullable=True),
    sa.Column('final_outcome', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_ledger_final_outcome'), 'decision_ledger', ['final_outcome'], unique=False)
    op.create_index(op.f('ix_decision_ledger_job_id'), 'decision_ledger', ['job_id'], unique=True)
    op.create_index(op.f('ix_decision_ledger_request_reference'), 'decision_ledger', ['request_reference'], unique=False)
    op.create_index(op.f('ix_decision_ledger_request_source'), 'decision_ledger', ['request_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_ledger_request_source'), table_name='decision_ledger')
    op.drop_index(op.f('ix_decision_ledger_request_reference'), table_name='decision_ledger')
    op.drop_index(op.f('ix_decision_ledger_job_id'), table_name='decision_ledger')
    op.drop_index(op.f('ix_decision_ledger_final_outcome'), table_name='decision_ledger')
    op.drop_table('decision_ledger')
    # ### end Alembic commands ###
